package escapesequence.UI;

import escapesequence.*; 

/**
 * @author Akera Griffith & Kaitlyn Morris
 * Escape Sequence Title Interface
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form TitleInterface
     */
    public MainMenu() {
        initComponents();
        backgroundLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/TitleScreen.jpg",590,300));
        tutorialButton.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/Video.png", 40, 40));
        settingsButton.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/Settings.png", 40, 40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        abortButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        settingsButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        singlePlayerButton = new javax.swing.JButton();
        singlePlayerButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        multiplayerButton = new javax.swing.JButton();
        multiplayerButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        tutorialButton = new javax.swing.JButton();
        tutorialLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(FontLoader.getVT323(48f));
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Escape Sequence");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 290, -1));

        abortButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        abortButton.setFont(FontLoader.getVT323(24f));
        abortButton.setContentAreaFilled(false);
        abortButton.setForeground(new java.awt.Color(255, 255, 255));
        abortButton.setText("Abort");
        abortButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        abortButton.setOpaque(false);
        abortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abortButtonActionPerformed(evt);
            }
        });
        jPanel1.add(abortButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 110, 50));

        settingsButton.setBorder(null);
        settingsButton.setOpaque(false);
        settingsButton.setContentAreaFilled(false);
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 40, 40));

        singlePlayerButton.setFont(FontLoader.getVT323(24f));
        singlePlayerButton.setContentAreaFilled(false);
        singlePlayerButton.setForeground(new java.awt.Color(255, 255, 255));
        singlePlayerButton.setText("Single Player");
        singlePlayerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        singlePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlePlayerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(singlePlayerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 150, 50));

        multiplayerButton.setFont(FontLoader.getVT323(24f));
        multiplayerButton.setContentAreaFilled(false);
        multiplayerButton.setForeground(new java.awt.Color(255, 255, 255));
        multiplayerButton.setText("Multiplayer");
        multiplayerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        multiplayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplayerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(multiplayerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 150, 50));

        tutorialButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        tutorialButton.setBorder(null);
        tutorialButton.setOpaque(false);
        tutorialButton.setContentAreaFilled(false);
        tutorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialButtonActionPerformed(evt);
            }
        });
        jPanel1.add(tutorialButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        tutorialLabel.setFont(FontLoader.getVT323(18f));
        tutorialLabel.setForeground(new java.awt.Color(255, 255, 255));
        tutorialLabel.setText("Tutorial");
        jPanel1.add(tutorialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 20));
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    //Abort
    private void abortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abortButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_abortButtonActionPerformed
    
    //Single Player
    private void singlePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singlePlayerButtonActionPerformed
        // TODO add your handling code here:
        SinglePlayer singlePlayer = new SinglePlayer();
        singlePlayer.setVisible(true);
        dispose();
    }//GEN-LAST:event_singlePlayerButtonActionPerformed

    //Multiplayer
    private void multiplayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplayerButtonActionPerformed
        // TODO add your handling code here:
        Multiplayer multiplayer = new Multiplayer();
        multiplayer.setVisible(true);
        dispose();
    }//GEN-LAST:event_multiplayerButtonActionPerformed

    //Settings
    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
        Settings settings = new Settings();
        settings.setVisible(true);
    }//GEN-LAST:event_settingsButtonActionPerformed
    
    //Tutorial
    private void tutorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialButtonActionPerformed
        // TODO add your handling code here:
        RulesScreen tutorial = new RulesScreen();
        tutorial.setVisible(true);
    }//GEN-LAST:event_tutorialButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abortButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multiplayerButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JButton singlePlayerButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton tutorialButton;
    private javax.swing.JLabel tutorialLabel;
    // End of variables declaration//GEN-END:variables
}
