package escapesequence.UI;

/**
 * @author Akera Griffith & Kaitlyn Morris
 * Escape Sequence Multiplayer Interface
 */

import javax.swing.JOptionPane;

public class Multiplayer extends javax.swing.JFrame {

    /**
     * Creates new form Multiplayer
     */
    public Multiplayer() {
        initComponents();
        setSize(1200,700);
        backgroundLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/WarningScreens.jpg",1200,700));
        arrowButton.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackArrow.png",40,40));
        starLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/Star.png",40,40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        captianLabel = new javax.swing.JLabel();
        nameInputField = new javax.swing.JTextField();
        accessCodeLabel = new javax.swing.JLabel();
        codeLabel = new javax.swing.JLabel();
        arrowButton = new javax.swing.JButton();
        starLabel = new javax.swing.JLabel();
        p2Label = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(FontLoader.getVT323(48f));
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Surviving Crew: 2");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 330, 40));

        startButton.setFont(FontLoader.getVT323(24f));
        startButton.setContentAreaFilled(false);
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        startButton.setText("Start");
        startButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        startButton.setOpaque(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 130, 40));

        captianLabel.setFont(FontLoader.getVT323(30f));
        captianLabel.setForeground(new java.awt.Color(255, 255, 255));
        captianLabel.setText("Ship Captain");
        jPanel1.add(captianLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        nameInputField.setBackground(new java.awt.Color(0, 0, 0));
        nameInputField.setFont(FontLoader.getVT323(18f));
        nameInputField.setForeground(new java.awt.Color(255, 255, 255));
        nameInputField.setText("Kaitlyn");
        nameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 140, 150, -1));

        accessCodeLabel.setFont(FontLoader.getVT323(24f));
        accessCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        accessCodeLabel.setText("Access Code");
        jPanel1.add(accessCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        codeLabel.setFont(FontLoader.getVT323(18f));
        codeLabel.setForeground(new java.awt.Color(255, 255, 255));
        codeLabel.setText("AF53GH");
        jPanel1.add(codeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        arrowButton.setContentAreaFilled(false);
        arrowButton.setBorder(null);
        arrowButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        arrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowButtonActionPerformed(evt);
            }
        });
        jPanel1.add(arrowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));
        jPanel1.add(starLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 40, 40));

        p2Label.setBackground(new java.awt.Color(51, 51, 51));
        p2Label.setFont(FontLoader.getVT323(24f));
        p2Label.setForeground(new java.awt.Color(255, 255, 255));
        p2Label.setText("Akera");
        p2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(p2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 60, -1));
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputFieldActionPerformed

    //Back Arrow
    private void arrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowButtonActionPerformed
        // TODO add your handling code here:
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_arrowButtonActionPerformed

    //Start
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        String name = nameInputField.getText().trim();

        //Validate name
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter a name to continue.",
                "No Name Entered",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        RulesScreen tutorial = new RulesScreen(RulesScreen.Source.MULTIPLAYER, name);
        tutorial.setVisible(true);
        dispose();
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Multiplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Multiplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Multiplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Multiplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Multiplayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accessCodeLabel;
    private javax.swing.JButton arrowButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel captianLabel;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameInputField;
    private javax.swing.JLabel p2Label;
    private javax.swing.JLabel starLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
