
package escapesequence.UI;

/**
 * @author Akera Griffith & Kaitlyn Morris
 * Escape Sequence Round3 Interface
 */
import escapesequence.*;
import java.util.ArrayList;

public class Round3 extends javax.swing.JFrame {

    /**
     * Creates new form Round3
     */
    GameController gameController;
    public Round3(GameController gameController) {
        this.gameController = gameController;
        initComponents();
        setSize(1200,700);
        backgroundLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/Round3.jpg",1200,700));
        pauseButton.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/Pause.png",40,40));
        //aiCardLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackOfCard.jpg",40,60));
        //deckLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackOfCards.jpg",60,40));
        aiSpecialtyCard1.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackOfSpecialty.jpg",40,40));
        specialtyCardLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/Peek.jpg",40,40));
        p1SpecialtyCardLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackOfSpecialty.jpg",40,40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pauseButton = new javax.swing.JButton();
        aiSpecialtyCard1 = new javax.swing.JLabel();
        p1SpecialtyCardLabel = new javax.swing.JLabel();
        specialtyCardTitle = new javax.swing.JLabel();
        specialtyCardLabel = new javax.swing.JLabel();
        p1Label = new javax.swing.JLabel();
        stayButton = new javax.swing.JButton();
        hitButton = new javax.swing.JButton();
        specialtyCard1Button = new javax.swing.JButton();
        aiCard1 = new javax.swing.JLabel();
        deckLabel1 = new javax.swing.JLabel();
        aiSpecialtyCard2 = new javax.swing.JLabel();
        p1SpecialtyCard2 = new javax.swing.JLabel();
        specialtyCard2Button = new javax.swing.JButton();
        specialtyCardTitle2 = new javax.swing.JLabel();
        p1Total = new javax.swing.JLabel();
        aiTotal = new javax.swing.JLabel();
        aiCard2 = new javax.swing.JLabel();
        aiCard3 = new javax.swing.JLabel();
        aiCard4 = new javax.swing.JLabel();
        aiCard5 = new javax.swing.JLabel();
        p1Card1 = new javax.swing.JLabel();
        p1Card2 = new javax.swing.JLabel();
        p1Card3 = new javax.swing.JLabel();
        p1Card4 = new javax.swing.JLabel();
        p1Card5 = new javax.swing.JLabel();
        p1Card6 = new javax.swing.JLabel();
        p1Card7 = new javax.swing.JLabel();
        p1Card8 = new javax.swing.JLabel();
        p1Card9 = new javax.swing.JLabel();
        aiCard6 = new javax.swing.JLabel();
        aiCard7 = new javax.swing.JLabel();
        aiCard8 = new javax.swing.JLabel();
        aiCard9 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pauseButton.setContentAreaFilled(false);
        pauseButton.setBorder(null);
        pauseButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pauseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 40, 40));
        jPanel1.add(aiSpecialtyCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 40, 40));
        jPanel1.add(p1SpecialtyCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 40, 40));

        specialtyCardTitle.setFont(FontLoader.getVT323(12f));
        specialtyCardTitle.setForeground(new java.awt.Color(0, 0, 0));
        specialtyCardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        specialtyCardTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(specialtyCardTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 40, 40));
        jPanel1.add(specialtyCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 40, 40));

        p1Label.setFont(FontLoader.getVT323(18f));
        p1Label.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(p1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 160, 30));

        stayButton.setFont(FontLoader.getVT323(24f));
        stayButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        stayButton.setForeground(new java.awt.Color(255, 255, 255));
        stayButton.setContentAreaFilled(false);
        stayButton.setText("Stay");
        stayButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(stayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 180, 80));

        hitButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        hitButton.setFont(FontLoader.getVT323(24f));
        hitButton.setContentAreaFilled(false);
        hitButton.setForeground(new java.awt.Color(255, 255, 255));
        hitButton.setText("Hit");
        hitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(hitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 180, 80));

        specialtyCard1Button.setFont(FontLoader.getVT323(14f));
        specialtyCard1Button.setBackground(new java.awt.Color(0, 0, 0, 100));
        specialtyCard1Button.setForeground(new java.awt.Color(255, 255, 255));
        specialtyCard1Button.setContentAreaFilled(false);
        specialtyCard1Button.setText("Use");
        specialtyCard1Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(specialtyCard1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 60, -1));

        aiCard1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(aiCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 50, 50));

        deckLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(deckLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 50, 50));
        jPanel1.add(aiSpecialtyCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 40, 40));
        jPanel1.add(p1SpecialtyCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 40, 40));

        specialtyCard2Button.setFont(FontLoader.getVT323(14f));
        specialtyCard2Button.setForeground(new java.awt.Color(255, 255, 255));
        specialtyCard2Button.setText("Use");
        specialtyCard2Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(specialtyCard2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 60, -1));

        specialtyCardTitle2.setFont(FontLoader.getVT323(12f));
        specialtyCardTitle2.setForeground(new java.awt.Color(0, 0, 0));
        specialtyCardTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        specialtyCardTitle2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(specialtyCardTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 40, 40));

        p1Total.setFont(FontLoader.getVT323(30f));
        p1Total.setForeground(new java.awt.Color(255, 255, 255));
        p1Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Total.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel1.add(p1Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 40, 30));

        aiTotal.setFont(FontLoader.getVT323(30f));
        aiTotal.setForeground(new java.awt.Color(255, 255, 255));
        aiTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aiTotal.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel1.add(aiTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 40, 30));

        aiCard2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(aiCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 50, 50));

        aiCard3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(aiCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 50, 50));

        aiCard4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(aiCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 50, 50));

        aiCard5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(aiCard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 50, 50));

        p1Card1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(p1Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 50, 50));

        p1Card2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(p1Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 50, 50));

        p1Card3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(p1Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 50, 50));

        p1Card4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(p1Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 50, 50));

        p1Card5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(p1Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 50, 50));

        p1Card6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(p1Card6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 50, 50));

        p1Card7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(p1Card7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 50, 50));

        p1Card8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(p1Card8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 50, 50));

        p1Card9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(p1Card9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 50, 50));

        aiCard6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(aiCard6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 50, 50));

        aiCard7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(aiCard7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 50, 50));

        aiCard8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(aiCard8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 50, 50));

        aiCard9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(aiCard9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 50, 50));
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Pause
    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        // TODO add your handling code here:
        PauseScreen pause = new PauseScreen();
        pause.setVisible(true);
    }//GEN-LAST:event_pauseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Round3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Round3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Round3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Round3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<escapesequence.Player> players = new ArrayList<>();
                players.add(new escapesequence.Player("Player 1"));
                new Round3(new escapesequence.GameController(players)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aiCard1;
    private javax.swing.JLabel aiCard2;
    private javax.swing.JLabel aiCard3;
    private javax.swing.JLabel aiCard4;
    private javax.swing.JLabel aiCard5;
    private javax.swing.JLabel aiCard6;
    private javax.swing.JLabel aiCard7;
    private javax.swing.JLabel aiCard8;
    private javax.swing.JLabel aiCard9;
    private javax.swing.JLabel aiSpecialtyCard1;
    private javax.swing.JLabel aiSpecialtyCard2;
    private javax.swing.JLabel aiTotal;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel deckLabel1;
    private javax.swing.JButton hitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel p1Card1;
    private javax.swing.JLabel p1Card2;
    private javax.swing.JLabel p1Card3;
    private javax.swing.JLabel p1Card4;
    private javax.swing.JLabel p1Card5;
    private javax.swing.JLabel p1Card6;
    private javax.swing.JLabel p1Card7;
    private javax.swing.JLabel p1Card8;
    private javax.swing.JLabel p1Card9;
    private javax.swing.JLabel p1Label;
    private javax.swing.JLabel p1SpecialtyCard2;
    private javax.swing.JLabel p1SpecialtyCardLabel;
    private javax.swing.JLabel p1Total;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton specialtyCard1Button;
    private javax.swing.JButton specialtyCard2Button;
    private javax.swing.JLabel specialtyCardLabel;
    private javax.swing.JLabel specialtyCardTitle;
    private javax.swing.JLabel specialtyCardTitle2;
    private javax.swing.JButton stayButton;
    // End of variables declaration//GEN-END:variables
}
