
package escapesequence.UI;

/**
 * @author Akera Griffith & Kaitlyn Morris
 * Escape Sequence Round2 Interface
 */


import escapesequence.*;
import java.util.ArrayList;

public class Round2 extends javax.swing.JFrame {

    /**
     * Creates new form Round2
     */
    GameController gameController;
    
    public Round2(GameController gameController) {
        this.gameController = gameController;
        initComponents();
        setSize(1200,700);
        backgroundLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/Round2.jpg",1200,700));
        pauseButton.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/Pause.png",40,40));
        aiCardLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackOfCard.jpg",40,60));
        deckLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackOfCards.jpg",60,40));
        aiSpecialtyCard1.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackOfSpecialty.jpg",40,40));
        specialtyCardLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/Peek.jpg",40,40));
        p2SpecialtyCardLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackOfSpecialty.jpg",40,40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pauseButton = new javax.swing.JButton();
        deckLabel = new javax.swing.JLabel();
        aiCardLabel = new javax.swing.JLabel();
        p2SpecialtyCardLabel = new javax.swing.JLabel();
        aiSpecialtyCard1 = new javax.swing.JLabel();
        specialtyCardTitle = new javax.swing.JLabel();
        specialtyCardLabel = new javax.swing.JLabel();
        p1Label = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        hitButton = new javax.swing.JButton();
        stayButton = new javax.swing.JButton();
        specialtyButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pauseButton.setContentAreaFilled(false);
        pauseButton.setBorder(null);
        pauseButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pauseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 40, 40));

        deckLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(deckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 60, 40));

        aiCardLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(aiCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 40, 60));
        jPanel1.add(p2SpecialtyCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 40, 40));
        jPanel1.add(aiSpecialtyCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 40, 40));

        specialtyCardTitle.setFont(FontLoader.getVT323(12f));
        specialtyCardTitle.setForeground(new java.awt.Color(0, 0, 0));
        specialtyCardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        specialtyCardTitle.setText("Peek");
        specialtyCardTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(specialtyCardTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 40, 40));
        jPanel1.add(specialtyCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 40, 40));

        p1Label.setFont(FontLoader.getVT323(18f));
        p1Label.setForeground(new java.awt.Color(255, 255, 255));
        p1Label.setText("Kaitlyn");
        jPanel1.add(p1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        nextButton.setFont(FontLoader.getVT323(18f));
        nextButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setContentAreaFilled(false);
        nextButton.setText("Next >>");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, 30));

        hitButton.setFont(FontLoader.getVT323(24f));
        hitButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        hitButton.setForeground(new java.awt.Color(255, 255, 255));
        hitButton.setContentAreaFilled(false);
        hitButton.setText("Hit");
        hitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(hitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 80, 40));

        stayButton.setFont(FontLoader.getVT323(24f));
        stayButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        stayButton.setForeground(new java.awt.Color(255, 255, 255));
        stayButton.setContentAreaFilled(false);
        stayButton.setText("Stay");
        stayButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(stayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 80, 40));

        specialtyButton.setFont(FontLoader.getVT323(14f));
        specialtyButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        specialtyButton.setForeground(new java.awt.Color(255, 255, 255));
        specialtyButton.setContentAreaFilled(false);
        specialtyButton.setText("Use");
        specialtyButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(specialtyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 60, -1));
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Pause
    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        // TODO add your handling code here:
        PauseScreen pause = new PauseScreen();
        pause.setVisible(true);
        
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        Round3 round3 = new Round3(gameController);
        round3.setVisible(true);
        dispose();
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Round2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Round2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Round2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Round2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<escapesequence.Player> players = new ArrayList<>();
                players.add(new escapesequence.Player("Player 1"));
                new Round2(new escapesequence.GameController(players)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aiCardLabel;
    private javax.swing.JLabel aiSpecialtyCard1;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel deckLabel;
    private javax.swing.JButton hitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel p1Label;
    private javax.swing.JLabel p2SpecialtyCardLabel;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton specialtyButton;
    private javax.swing.JLabel specialtyCardLabel;
    private javax.swing.JLabel specialtyCardTitle;
    private javax.swing.JButton stayButton;
    // End of variables declaration//GEN-END:variables
}
