
package escapesequence.UI;

/**
 * @author Akera Griffith & Kaitlyn Morris
 * Escape Sequence Round 1 Interface
 */
public class Round1 extends javax.swing.JFrame {

    /** Creates new form Round1 */
    public Round1() {
        initComponents();
        backgroundLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/Round1.jpg",590,300));
        pauseButton.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/Pause.png",40,40));
        aiCardLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackOfCard.jpg",40,60));
        deckLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackOfCards.jpg",60,40));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p1CardButton1 = new javax.swing.JButton();
        aiCardButton1 = new javax.swing.JButton();
        deckLabel = new javax.swing.JLabel();
        pauseButton = new javax.swing.JButton();
        p2CardButton2 = new javax.swing.JButton();
        aiCardLabel = new javax.swing.JLabel();
        p2CardButton1 = new javax.swing.JButton();
        p1CardButton2 = new javax.swing.JButton();
        p2Label = new javax.swing.JLabel();
        p1Label = new javax.swing.JLabel();
        hitButton = new javax.swing.JButton();
        stayButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(590, 300));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1CardButton1.setBackground(new java.awt.Color(153, 153, 153));
        p1CardButton1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        p1CardButton1.setForeground(new java.awt.Color(0, 0, 0));
        p1CardButton1.setText("9");
        p1CardButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p1CardButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1CardButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(p1CardButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 40, 60));

        aiCardButton1.setBackground(new java.awt.Color(153, 153, 153));
        aiCardButton1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        aiCardButton1.setForeground(new java.awt.Color(0, 0, 0));
        aiCardButton1.setText("7");
        aiCardButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(aiCardButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 40, 60));

        deckLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        deckLabel.setOpaque(true);
        jPanel1.add(deckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 60, 40));

        pauseButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        pauseButton.setContentAreaFilled(false);
        pauseButton.setBorder(null);
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pauseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 40, 40));

        p2CardButton2.setBackground(new java.awt.Color(153, 153, 153));
        p2CardButton2.setFont(new java.awt.Font("Sans Serif Collection", 0, 24)); // NOI18N
        p2CardButton2.setForeground(new java.awt.Color(0, 0, 0));
        p2CardButton2.setText("6");
        p2CardButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p2CardButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2CardButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(p2CardButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 40, 60));

        aiCardLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        aiCardLabel.setOpaque(true);
        jPanel1.add(aiCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 40, 60));

        p2CardButton1.setBackground(new java.awt.Color(153, 153, 153));
        p2CardButton1.setFont(new java.awt.Font("Sans Serif Collection", 0, 24)); // NOI18N
        p2CardButton1.setForeground(new java.awt.Color(0, 0, 0));
        p2CardButton1.setText("1");
        p2CardButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(p2CardButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 40, 60));

        p1CardButton2.setBackground(new java.awt.Color(153, 153, 153));
        p1CardButton2.setFont(new java.awt.Font("Sans Serif Collection", 0, 24)); // NOI18N
        p1CardButton2.setForeground(new java.awt.Color(0, 0, 0));
        p1CardButton2.setText("5");
        p1CardButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(p1CardButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 40, 60));

        p2Label.setFont(FontLoader.getVT323(18f));
        p2Label.setForeground(new java.awt.Color(255, 255, 255));
        p2Label.setText("Akera");
        jPanel1.add(p2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        p1Label.setFont(FontLoader.getVT323(18f));
        p1Label.setForeground(new java.awt.Color(255, 255, 255));
        p1Label.setText("Kaitlyn");
        jPanel1.add(p1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        hitButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        hitButton.setFont(FontLoader.getVT323(24f));
        hitButton.setForeground(new java.awt.Color(255, 255, 255));
        hitButton.setContentAreaFilled(false);
        hitButton.setText("Hit");
        hitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(hitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 80, 40));

        stayButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        stayButton.setFont(FontLoader.getVT323(24f));
        stayButton.setContentAreaFilled(false);
        stayButton.setForeground(new java.awt.Color(255, 255, 255));
        stayButton.setText("Stay");
        stayButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(stayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 80, 40));

        nextButton.setFont(FontLoader.getVT323(18f));
        nextButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setContentAreaFilled(false);
        nextButton.setText("Next >>");
        nextButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 70, 30));
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Pause
    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        // TODO add your handling code here:
        PauseScreen pause = new PauseScreen();
        pause.setVisible(true);
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void p1CardButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1CardButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1CardButton1ActionPerformed

    private void p2CardButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2CardButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2CardButton2ActionPerformed

    //Next
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        Round2 round2 = new Round2();
        round2.setVisible(true);
        dispose();
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Round1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Round1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Round1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Round1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Round1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aiCardButton1;
    private javax.swing.JLabel aiCardLabel;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel deckLabel;
    private javax.swing.JButton hitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton p1CardButton1;
    private javax.swing.JButton p1CardButton2;
    private javax.swing.JLabel p1Label;
    private javax.swing.JButton p2CardButton1;
    private javax.swing.JButton p2CardButton2;
    private javax.swing.JLabel p2Label;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton stayButton;
    // End of variables declaration//GEN-END:variables

}
