package escapesequence.UI;

/**
 * @author Akera Griffith & Kaitlyn Morris
 * Player(s) escape the ship game over screen
 */

import escapesequence.GameController;
import java.util.ArrayList;

public class EscapeScreen extends javax.swing.JFrame {
    
private GameController gameController;
    
    public EscapeScreen(GameController gameController) {
        this.gameController = gameController;
        initComponents();
        int sw = 1200, sh = 700;
        java.awt.Dimension fixed = new java.awt.Dimension(sw, sh);
        jPanel1.setPreferredSize(fixed);
        jPanel1.setMinimumSize(fixed);
        backgroundLabel.setBounds(0, 0, sw, sh);
        setSize(sw, sh);
        setResizable(false);
        setLocationRelativeTo(null);
        SoundManager.enableButtonSounds(this.getContentPane());
        backgroundLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/EscapeSequence.png", sw, sh));
        populateCadets();
    }

    // Populates the cadet name labels with the names of surviving players
    private void populateCadets() {
        java.util.ArrayList<escapesequence.Player> survivors = gameController.getSurvivors();
        javax.swing.JLabel[] cadets = {cadet1, cadet2, cadet3};
        for (javax.swing.JLabel c : cadets) {
            c.setText("");
            c.setVisible(false);
        }
        for (int i = 0; i < survivors.size() && i < cadets.length; i++) {
            cadets[i].setText(survivors.get(i).getName());
            cadets[i].setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainMenu = new javax.swing.JButton();
        cadet1 = new javax.swing.JLabel();
        cadet2 = new javax.swing.JLabel();
        cadet3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setSize(new java.awt.Dimension(1200, 700));

        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainMenu.setBackground(new java.awt.Color(0, 0, 0));
        mainMenu.setFont(new java.awt.Font("VT323", 0, 48)); // NOI18N
        mainMenu.setForeground(new java.awt.Color(255, 255, 255));
        mainMenu.setText("Main Menu");
        mainMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainMenu.setContentAreaFilled(false);
        mainMenu.setFocusPainted(false);
        mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuActionPerformed(evt);
            }
        });
        jPanel1.add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 240, 100));

        cadet1.setFont(FontLoader.getVT323(65f));
        cadet1.setForeground(new java.awt.Color(255, 255, 255));
        cadet1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cadet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 260, 60));

        cadet2.setFont(FontLoader.getVT323(65f));
        cadet2.setForeground(new java.awt.Color(255, 255, 255));
        cadet2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cadet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 260, 60));

        cadet3.setFont(FontLoader.getVT323(65f));
        cadet3.setForeground(new java.awt.Color(255, 255, 255));
        cadet3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cadet3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 260, 60));

        jLabel1.setFont(new java.awt.Font("VT323", 0, 170)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escaped");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 216, 1200, 210));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pictures/EscapeSequence.png"))); // NOI18N
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
        // TODO add your handling code here:
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_mainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscapeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscapeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscapeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscapeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<escapesequence.Player> players = new ArrayList<>();
                players.add(new escapesequence.Player("Player 1"));
                new GameOver(new escapesequence.GameController(players)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel cadet1;
    private javax.swing.JLabel cadet2;
    private javax.swing.JLabel cadet3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainMenu;
    // End of variables declaration//GEN-END:variables
}
