package escapesequence.UI;

/**
 * @author Akera Griffith & Kaitlyn Morris
 * Escape Sequence Multiplayer Interface
 */


public class Multiplayer extends javax.swing.JFrame {

    /**
     * Creates new form Multiplayer
     */
    private int selectedPlayerCount = 2;
    
    public Multiplayer() {
        initComponents();
        java.awt.Dimension screen = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int sw = screen.width, sh = screen.height;
        jPanel1.setPreferredSize(screen);
        jPanel1.setMinimumSize(screen);
        backgroundLabel.setBounds(0, 0, sw, sh);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        SoundManager.enableButtonSounds(this.getContentPane());
        //hideAllCadetFields();
        backgroundLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/WarningScreens.png", sw, sh));
        arrowButton.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackArrow.png",40,40));
        
        updateVisibleFields(selectedPlayerCount);
    }

    
    private void updateVisibleFields(int totalPlayers) {
        // totalPlayers includes the captain, cadets = totalPlayers - 1
        p2NameInput.setVisible(totalPlayers >= 2);
        cadetLabel1.setVisible(totalPlayers >= 2);
        p3NameInput.setVisible(totalPlayers >= 3);
        cadetLabel2.setVisible(totalPlayers >= 3);
        p4NameInput.setVisible(totalPlayers >= 4);
        cadetLabel3.setVisible(totalPlayers >= 4);
        p5NameInput.setVisible(totalPlayers >= 5);
        cadetLabel4.setVisible(totalPlayers >= 5);
        p6NameInput.setVisible(totalPlayers >= 6);
        cadetLabel5.setVisible(totalPlayers >= 6);
        playersTotal.setText(String.valueOf(totalPlayers));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        captianLabel = new javax.swing.JLabel();
        nameInputField = new javax.swing.JTextField();
        arrowButton = new javax.swing.JButton();
        multiplayerSelectionTitle = new javax.swing.JLabel();
        twoPlayersButton = new javax.swing.JButton();
        threePlayersButton = new javax.swing.JButton();
        fourPlayersButton = new javax.swing.JButton();
        fivePlayersButton = new javax.swing.JButton();
        sixPlayersButton = new javax.swing.JButton();
        p2NameInput = new javax.swing.JTextField();
        p3NameInput = new javax.swing.JTextField();
        p4NameInput = new javax.swing.JTextField();
        p5NameInput = new javax.swing.JTextField();
        p6NameInput = new javax.swing.JTextField();
        cadetLabel1 = new javax.swing.JLabel();
        cadetLabel2 = new javax.swing.JLabel();
        cadetLabel3 = new javax.swing.JLabel();
        cadetLabel4 = new javax.swing.JLabel();
        cadetLabel5 = new javax.swing.JLabel();
        playersTotal = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(FontLoader.getVT323(48f));
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleLabel.setText("Surviving Crew: ");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 360, 50));

        startButton.setFont(FontLoader.getVT323(24f));
        startButton.setContentAreaFilled(false);
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        startButton.setOpaque(false);
        startButton.setText("Start");
        startButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        startButton.setFocusPainted(false);
        startButton.setOpaque(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, 220, 70));

        captianLabel.setFont(FontLoader.getVT323(40f));
        captianLabel.setForeground(new java.awt.Color(255, 255, 255));
        captianLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        captianLabel.setText("Ship Captain");
        jPanel1.add(captianLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 210, 40));

        nameInputField.setBackground(new java.awt.Color(0, 0, 0));
        nameInputField.setCaretColor(new java.awt.Color(198, 40, 40));
        nameInputField.setFont(FontLoader.getVT323(24f));
        nameInputField.setForeground(new java.awt.Color(255, 255, 255));
        nameInputField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 150, 40));

        arrowButton.setContentAreaFilled(false);
        arrowButton.setBorder(null);
        arrowButton.setFocusPainted(false);
        arrowButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        arrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowButtonActionPerformed(evt);
            }
        });
        jPanel1.add(arrowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        multiplayerSelectionTitle.setFont(FontLoader.getVT323(48f));

        multiplayerSelectionTitle.setForeground(new java.awt.Color(255, 255, 255));
        multiplayerSelectionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multiplayerSelectionTitle.setText("How Many Remaining Cadets?");
        jPanel1.add(multiplayerSelectionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 600, 50));

        twoPlayersButton.setFont(FontLoader.getVT323(30f));

        twoPlayersButton.setContentAreaFilled(false);
        twoPlayersButton.setForeground(new java.awt.Color(255, 255, 255));
        twoPlayersButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        twoPlayersButton.setOpaque(false);
        twoPlayersButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        twoPlayersButton.setText("1");
        twoPlayersButton.setFocusPainted(false);
        twoPlayersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoPlayersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(twoPlayersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 70, -1));

        threePlayersButton.setFont(FontLoader.getVT323(30f));

        threePlayersButton.setContentAreaFilled(false);
        threePlayersButton.setForeground(new java.awt.Color(255, 255, 255));
        threePlayersButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        threePlayersButton.setOpaque(false);

        threePlayersButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        threePlayersButton.setText("2");
        threePlayersButton.setFocusPainted(false);
        threePlayersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threePlayersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(threePlayersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 70, -1));

        fourPlayersButton.setFont(FontLoader.getVT323(30f));

        fourPlayersButton.setContentAreaFilled(false);
        fourPlayersButton.setForeground(new java.awt.Color(255, 255, 255));
        fourPlayersButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        fourPlayersButton.setOpaque(false);

        fourPlayersButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        fourPlayersButton.setText("3");
        fourPlayersButton.setFocusPainted(false);
        fourPlayersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourPlayersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fourPlayersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 70, -1));

        fivePlayersButton.setFont(FontLoader.getVT323(30f));

        fivePlayersButton.setContentAreaFilled(false);
        fivePlayersButton.setForeground(new java.awt.Color(255, 255, 255));
        fivePlayersButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        fivePlayersButton.setOpaque(false);
        fivePlayersButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        fivePlayersButton.setText("4");
        fivePlayersButton.setFocusPainted(false);
        fivePlayersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivePlayersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fivePlayersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 70, -1));

        sixPlayersButton.setFont(FontLoader.getVT323(30f));

        sixPlayersButton.setContentAreaFilled(false);
        sixPlayersButton.setForeground(new java.awt.Color(255, 255, 255));
        sixPlayersButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        sixPlayersButton.setOpaque(false);

        sixPlayersButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0)));
        sixPlayersButton.setText("5");
        sixPlayersButton.setFocusPainted(false);
        sixPlayersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixPlayersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sixPlayersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 70, -1));

        p2NameInput.setFont(new java.awt.Font("VT323", 0, 24)); // NOI18N
        p2NameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2NameInputActionPerformed(evt);
            }
        });
        jPanel1.add(p2NameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 140, 40));
        p2NameInput.setBackground(java.awt.Color.BLACK);
        p2NameInput.setForeground(java.awt.Color.WHITE);
        p2NameInput.setCaretColor(new java.awt.Color(198, 40, 40));

        p3NameInput.setBackground(java.awt.Color.BLACK);
        p3NameInput.setForeground(java.awt.Color.WHITE);
        p3NameInput.setCaretColor(new java.awt.Color(198, 40, 40));
        p3NameInput.setFont(new java.awt.Font("VT323", 0, 24)); // NOI18N
        p3NameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(p3NameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 140, 40));

        p4NameInput.setBackground(java.awt.Color.BLACK);
        p4NameInput.setForeground(java.awt.Color.WHITE);
        p4NameInput.setCaretColor(new java.awt.Color(198, 40, 40));
        p4NameInput.setFont(new java.awt.Font("VT323", 0, 24)); // NOI18N
        p4NameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(p4NameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 140, 40));

        p5NameInput.setBackground(java.awt.Color.BLACK);
        p5NameInput.setForeground(java.awt.Color.WHITE);
        p5NameInput.setCaretColor(new java.awt.Color(198, 40, 40));
        p5NameInput.setFont(new java.awt.Font("VT323", 0, 24)); // NOI18N
        p5NameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p5NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5NameInputActionPerformed(evt);
            }
        });
        jPanel1.add(p5NameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 140, 40));

        p6NameInput.setBackground(java.awt.Color.BLACK);
        p6NameInput.setForeground(java.awt.Color.WHITE);
        p6NameInput.setCaretColor(new java.awt.Color(198, 40, 40));
        p6NameInput.setFont(new java.awt.Font("VT323", 0, 24)); // NOI18N
        p6NameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(p6NameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, 140, 40));

        cadetLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cadetLabel1.setText("Cadet 1:");
        jPanel1.add(cadetLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 150, 40));
        cadetLabel1.setFont(FontLoader.getVT323(40f));
        cadetLabel1.setForeground(java.awt.Color.WHITE);

        cadetLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cadetLabel2.setText("Cadet 2:");
        jPanel1.add(cadetLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 150, 40));
        cadetLabel2.setFont(FontLoader.getVT323(40f));
        cadetLabel2.setForeground(java.awt.Color.WHITE);

        cadetLabel3.setFont(FontLoader.getVT323(40f));
        cadetLabel3.setForeground(java.awt.Color.WHITE);
        cadetLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cadetLabel3.setText("Cadet 3:");
        jPanel1.add(cadetLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 150, 40));

        cadetLabel4.setFont(FontLoader.getVT323(40f));
        cadetLabel4.setForeground(java.awt.Color.WHITE);
        cadetLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cadetLabel4.setText("Cadet 4:");
        jPanel1.add(cadetLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 150, 40));

        cadetLabel5.setFont(FontLoader.getVT323(40f));
        cadetLabel5.setForeground(java.awt.Color.WHITE);
        cadetLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cadetLabel5.setText("Cadet 5:");
        jPanel1.add(cadetLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 150, 40));

        playersTotal.setBackground(new java.awt.Color(0, 0, 0));
        playersTotal.setFont(new java.awt.Font("VT323", 0, 48)); // NOI18N
        playersTotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(playersTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 40, 50));
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputFieldActionPerformed

    //Back Arrow
    private void arrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowButtonActionPerformed
        // TODO add your handling code here:
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_arrowButtonActionPerformed

    //Start
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Collect and validate all names
        String captainName = nameInputField.getText().trim();
        if (captainName.isEmpty()) {
            GameDialog.show(this, "Please enter the Ship Captain's name.");
            return;
        }

        javax.swing.JTextField[] cadetFields = {
            p2NameInput, p3NameInput, p4NameInput, p5NameInput, p6NameInput
        };

        java.util.ArrayList<escapesequence.Player> players = new java.util.ArrayList<>();
        players.add(new escapesequence.Player(captainName));

        for (int i = 0; i < selectedPlayerCount - 1; i++) {
            String name = cadetFields[i].getText().trim();
            if (name.isEmpty()) {
                GameDialog.show(this, "Please enter a name for Cadet " + (i + 1) + ".");
                return;
            }
            players.add(new escapesequence.Player(name));
        }

        // Create controller with all players in MULTIPLAYER mode
        escapesequence.GameController gc = new escapesequence.GameController(
                players, escapesequence.GameController.GameMode.MULTIPLAYER);

        RulesScreen tutorial = new RulesScreen(RulesScreen.Source.MULTIPLAYER, "", gc);
        tutorial.setVisible(true);
        dispose();
    }

    private void threePlayersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threePlayersButtonActionPerformed
        // TODO add your handling code here:
        selectedPlayerCount = 3;
        updateVisibleFields(selectedPlayerCount);
    }//GEN-LAST:event_threePlayersButtonActionPerformed

    private void fourPlayersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourPlayersButtonActionPerformed
        // TODO add your handling code here:
        selectedPlayerCount = 4;
        updateVisibleFields(selectedPlayerCount);
    }//GEN-LAST:event_fourPlayersButtonActionPerformed

    private void fivePlayersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivePlayersButtonActionPerformed
        // TODO add your handling code here:
        selectedPlayerCount = 5;
        updateVisibleFields(selectedPlayerCount);
    }//GEN-LAST:event_fivePlayersButtonActionPerformed

    private void sixPlayersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixPlayersButtonActionPerformed
        // TODO add your handling code here:
        selectedPlayerCount = 6;
        updateVisibleFields(selectedPlayerCount);
    }//GEN-LAST:event_sixPlayersButtonActionPerformed

    private void p2NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2NameInputActionPerformed

    private void p5NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p5NameInputActionPerformed

    private void twoPlayersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoPlayersButtonActionPerformed
        // TODO add your handling code here:
        selectedPlayerCount = 2;
        updateVisibleFields(selectedPlayerCount);
    }//GEN-LAST:event_twoPlayersButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Multiplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Multiplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Multiplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Multiplayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Multiplayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arrowButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel cadetLabel1;
    private javax.swing.JLabel cadetLabel2;
    private javax.swing.JLabel cadetLabel3;
    private javax.swing.JLabel cadetLabel4;
    private javax.swing.JLabel cadetLabel5;
    private javax.swing.JLabel captianLabel;
    private javax.swing.JButton fivePlayersButton;
    private javax.swing.JButton fourPlayersButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel multiplayerSelectionTitle;
    private javax.swing.JTextField nameInputField;
    private javax.swing.JTextField p2NameInput;
    private javax.swing.JTextField p3NameInput;
    private javax.swing.JTextField p4NameInput;
    private javax.swing.JTextField p5NameInput;
    private javax.swing.JTextField p6NameInput;
    private javax.swing.JLabel playersTotal;
    private javax.swing.JButton sixPlayersButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton threePlayersButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton twoPlayersButton;
    // End of variables declaration//GEN-END:variables
}
