
package escapesequence.UI;

/**
 * @author Akera Griffith & Kaitlyn Morris
 * Escape Sequence Pause Interface
 */
public class PauseScreen extends javax.swing.JFrame {

    /**
     * Creates new form PauseScreen
     */
    public PauseScreen() {
        initComponents();
        java.awt.Dimension screen = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int sw = screen.width, sh = screen.height;
        jPanel1.setPreferredSize(screen);
        jPanel1.setMinimumSize(screen);
        backgroundLabel.setBounds(0, 0, sw, sh);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        backgroundLabel.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/Space2.png", sw, sh));
        backButton.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/BackArrow.png",50,50));
        tutorialButton.setIcon(ResourceLoader.loadImageScaled("/assets/pictures/tutorial.png",50,50));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        tutorialButton = new javax.swing.JButton();
        tutorialLabel = new javax.swing.JLabel();
        resumeButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(FontLoader.getVT323(65f));
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Paused");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 800, 40));

        backButton.setContentAreaFilled(false);
        backButton.setBorder(null);
        backButton.setFocusPainted(false);
        backButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        tutorialButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        tutorialButton.setContentAreaFilled(false);
        tutorialButton.setBorder(null);
        tutorialButton.setFocusPainted(false);
        tutorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialButtonActionPerformed(evt);
            }
        });
        jPanel1.add(tutorialButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 50, 50));

        tutorialLabel.setFont(FontLoader.getVT323(18f));
        tutorialLabel.setForeground(new java.awt.Color(255, 255, 255));
        tutorialLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tutorialLabel.setText("Tutorial");
        jPanel1.add(tutorialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 70, 20));

        resumeButton.setFont(FontLoader.getVT323(30f));
        resumeButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        resumeButton.setForeground(new java.awt.Color(255, 255, 255));
        resumeButton.setContentAreaFilled(false);
        resumeButton.setText("Resume");
        resumeButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black));
        resumeButton.setContentAreaFilled(false);
        resumeButton.setFocusPainted(false);
        resumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resumeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 150, 60));

        quitButton.setFont(FontLoader.getVT323(30f));
        quitButton.setBackground(new java.awt.Color(0, 0, 0, 100));
        quitButton.setForeground(new java.awt.Color(255, 255, 255));
        quitButton.setContentAreaFilled(false);
        quitButton.setText("Quit");
        quitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        quitButton.setFocusPainted(false);
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(quitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 150, 60));

        settingsButton.setFont(FontLoader.getVT323(30f));
        settingsButton.setForeground(new java.awt.Color(255, 255, 255));
        settingsButton.setText("Settings");
        settingsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black));
        settingsButton.setContentAreaFilled(false);
        settingsButton.setFocusPainted(false);
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 150, 60));
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Settings
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    //Quit
    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        if (GameDialog.confirm(this, "Are you sure you want to quit?")) {
            System.exit(0); 
        }
    }//GEN-LAST:event_quitButtonActionPerformed
    
    //Tutorial
    private void tutorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialButtonActionPerformed
        // TODO add your handling code here:
        RulesScreen tutorial = new RulesScreen(RulesScreen.Source.PAUSE,"");
        tutorial.setVisible(true);
    }//GEN-LAST:event_tutorialButtonActionPerformed

    //Resume
    private void resumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_resumeButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
        Settings settings = new Settings();
        settings.setLocationRelativeTo(this); 
        settings.setVisible(true);
    }//GEN-LAST:event_settingsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PauseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PauseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PauseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PauseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PauseScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton resumeButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton tutorialButton;
    private javax.swing.JLabel tutorialLabel;
    // End of variables declaration//GEN-END:variables
}
